In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df = pd.read_csv('/content/drive/My Drive/Wine.csv')
df

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6      127.0           2.80   
1      13.20        1.78  2.14          11.2      100.0           2.65   
2      13.16        2.36  2.67          18.6      101.0           2.80   
3      14.37        1.95  2.50          16.8      113.0           3.85   
4      13.24        2.59  2.87          21.0      118.0           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5       95.0           1.68   
174    13.40        3.91  2.48          23.0      102.0           1.80   
175    13.27        4.28  2.26          20.0      120.0           1.59   
176    13.17        2.59  2.37          20.0      120.0           1.65   
177    14.13        4.10  2.74          24.5       96.0           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline Customer_Segment  
0     3.92     1065              YES  
1     3.40     1050               NO  
2     3.17     1185              YES  
3     3.45     1480               NO  
4     2.93      735              YES  
..     ...      ...              ...  
173   1.74      740               NO  
174   1.56      750              YES  
175   1.56      835               NO  
176   1.62      840              YES  
177   1.60      560               NO  

[178 rows x 14 columns]

In [4]:
df.dtypes

Alcohol                 float64
Malic_Acid              float64
Ash                     float64
Ash_Alcanity            float64
Magnesium               float64
Total_Phenols           float64
Flavanoids              float64
Nonflavanoid_Phenols    float64
Proanthocyanins         float64
Color_Intensity         float64
Hue                     float64
OD280                   float64
Proline                   int64
Customer_Segment         object
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Alcohol               175 non-null    float64
 1   Malic_Acid            178 non-null    float64
 2   Ash                   178 non-null    float64
 3   Ash_Alcanity          178 non-null    float64
 4   Magnesium             169 non-null    float64
 5   Total_Phenols         170 non-null    float64
 6   Flavanoids            174 non-null    float64
 7   Nonflavanoid_Phenols  178 non-null    float64
 8   Proanthocyanins       162 non-null    float64
 9   Color_Intensity       178 non-null    float64
 10  Hue                   178 non-null    float64
 11  OD280                 174 non-null    float64
 12  Proline               178 non-null    int64  
 13  Customer_Segment      178 non-null    object 
dtypes: float64(12), int64(1), object(1)
memory usage: 19.6+ KB


In [6]:
df.shape

(178, 14)

In [7]:
df.describe()

Alcohol  Malic_Acid         Ash  Ash_Alcanity   Magnesium  \
count  175.000000  178.000000  178.000000    178.000000  169.000000   
mean    12.991314    2.336348    2.366517     19.494944   99.721893   
std      0.813333    1.117146    0.274344      3.339564   14.594913   
min     11.030000    0.740000    1.360000     10.600000   70.000000   
25%     12.350000    1.602500    2.210000     17.200000   88.000000   
50%     13.050000    1.865000    2.360000     19.500000   98.000000   
75%     13.675000    3.082500    2.557500     21.500000  108.000000   
max     14.830000    5.800000    3.230000     30.000000  162.000000   

       Total_Phenols  Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  \
count     170.000000  174.000000            178.000000       162.000000   
mean        2.299529    1.998161              0.361854         1.567407   
std         0.615284    0.987299              0.124453         0.556095   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.782500    1.125000              0.270000         1.242500   
50%         2.355000    2.100000              0.340000         1.535000   
75%         2.800000    2.787500              0.437500         1.942500   
max         3.880000    5.080000              0.660000         3.580000   

       Color_Intensity         Hue       OD280      Proline  
count       178.000000  178.000000  174.000000   178.000000  
mean          5.058090    0.957449    2.586322   746.893258  
std           2.318286    0.228572    0.697293   314.907474  
min           1.280000    0.480000    1.270000   278.000000  
25%           3.220000    0.782500    1.922500   500.500000  
50%           4.690000    0.965000    2.775000   673.500000  
75%           6.200000    1.120000    3.160000   985.000000  
max          13.000000    1.710000    3.920000  1680.000000

In [8]:
df.groupby('Customer_Segment').size()

Customer_Segment
NO     89
YES    89
dtype: int64

In [9]:
df.isnull().sum()

Alcohol                  3
Malic_Acid               0
Ash                      0
Ash_Alcanity             0
Magnesium                9
Total_Phenols            8
Flavanoids               4
Nonflavanoid_Phenols     0
Proanthocyanins         16
Color_Intensity          0
Hue                      0
OD280                    4
Proline                  0
Customer_Segment         0
dtype: int64

In [10]:
X = df.iloc[:,0:13].values
Y = df.iloc[:, 13].values

In [11]:
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [12]:
Y

array(['YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES'

In [13]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean", fill_value=None, verbose=1, copy=True)
imputer = imputer.fit(X[:, 0:13])
X[:, 0: 13] = imputer.transform(X[:, 0:13])
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [14]:
from sklearn.preprocessing import LabelEncoder
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)
Y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0])

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.1, random_state = 7)

In [16]:
X_train

array([[1.383e+01, 1.650e+00, 2.600e+00, ..., 1.240e+00, 3.370e+00,
        1.265e+03],
       [1.421e+01, 4.040e+00, 2.440e+00, ..., 8.700e-01, 3.330e+00,
        1.080e+03],
       [1.196e+01, 1.090e+00, 2.300e+00, ..., 9.900e-01, 3.130e+00,
        8.860e+02],
       ...,
       [1.237e+01, 1.170e+00, 1.920e+00, ..., 1.120e+00, 3.480e+00,
        5.100e+02],
       [1.305e+01, 2.050e+00, 3.220e+00, ..., 1.130e+00, 3.200e+00,
        8.300e+02],
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02]])

In [17]:
X_test

array([[1.28700000e+01, 4.61000000e+00, 2.48000000e+00, 2.15000000e+01,
        8.60000000e+01, 1.70000000e+00, 6.50000000e-01, 4.70000000e-01,
        8.60000000e-01, 7.65000000e+00, 5.40000000e-01, 1.86000000e+00,
        6.25000000e+02],
       [1.32800000e+01, 1.64000000e+00, 2.84000000e+00, 1.55000000e+01,
        1.10000000e+02, 2.60000000e+00, 2.68000000e+00, 3.40000000e-01,
        1.36000000e+00, 4.60000000e+00, 1.09000000e+00, 2.78000000e+00,
        8.80000000e+02],
       [1.28200000e+01, 3.37000000e+00, 2.30000000e+00, 1.95000000e+01,
        8.80000000e+01, 1.48000000e+00, 6.60000000e-01, 4.00000000e-01,
        9.70000000e-01, 1.02600000e+01, 7.20000000e-01, 1.75000000e+00,
        6.85000000e+02],
       [1.27700000e+01, 2.39000000e+00, 2.28000000e+00, 1.95000000e+01,
        8.60000000e+01, 1.39000000e+00, 5.10000000e-01, 4.80000000e-01,
        6.40000000e-01, 9.89999900e+00, 5.70000000e-01, 1.63000000e+00,
        4.70000000e+02],
       [1.24300000e+01, 1.53000000e+

In [18]:
Y_train

array([0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0])

In [19]:
Y_test

array([0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [20]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [21]:
X_train

array([[ 1.00801947, -0.59825689,  0.84005093, ...,  1.25904718,
         1.1229713 ,  1.56570181],
       [ 1.48305789,  1.54662811,  0.27037401, ..., -0.41688917,
         1.06500262,  0.98948212],
       [-1.32966959, -1.10082409, -0.2280933 , ...,  0.12665776,
         0.77515925,  0.38523012],
       ...,
       [-0.81712814, -1.02902877, -1.581076  , ...,  0.71550026,
         1.28238515, -0.78589747],
       [ 0.03294061, -0.23928032,  3.04754902, ...,  0.76079583,
         0.87660443,  0.21080686],
       [ 0.30796285,  1.76201406, -0.37051253, ..., -1.68516532,
        -1.50011125,  0.22638036]])

In [22]:
X_test

array([[-1.92077588e-01,  2.05816973e+00,  4.12793240e-01,
         5.88996888e-01, -9.80162194e-01, -9.78031050e-01,
        -1.39929537e+00,  8.70377032e-01, -1.36461477e+00,
         1.15664612e+00, -1.91164321e+00, -1.06534619e+00,
        -4.27706852e-01],
       [ 3.20463864e-01, -6.07231304e-01,  1.69456632e+00,
        -1.14707008e+00,  6.64507979e-01,  4.85407146e-01,
         6.76455481e-01, -1.57082801e-01, -4.21233044e-01,
        -2.16094058e-01,  5.79613527e-01,  2.67933340e-01,
         3.66541911e-01],
       [-2.54582643e-01,  9.45342361e-01, -2.28093300e-01,
         1.03078976e-02, -8.43106346e-01, -1.33576039e+00,
        -1.38907000e+00,  3.17129429e-01, -1.15707079e+00,
         2.33135165e+00, -1.09632282e+00, -1.22476004e+00,
        -2.40824790e-01],
       [-3.17087698e-01,  6.58497645e-02, -2.99302915e-01,
         1.03078976e-02, -9.80162194e-01, -1.48210421e+00,
        -1.54245060e+00,  9.49412404e-01, -1.77970273e+00,
         2.16932285e+00, -1.77575648e

In [23]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [24]:
X_train

array([[0.70760234, 0.1798419 , 0.6631016 , ..., 0.78350515, 0.79245283,
        0.70399429],
       [0.81871345, 0.65217391, 0.57754011, ..., 0.40206186, 0.77735849,
        0.57203994],
       [0.16081871, 0.06916996, 0.5026738 , ..., 0.5257732 , 0.70188679,
        0.43366619],
       ...,
       [0.28070175, 0.08498024, 0.29946524, ..., 0.65979381, 0.83396226,
        0.16547789],
       [0.47953216, 0.25889328, 0.99465241, ..., 0.67010309, 0.72830189,
        0.39372325],
       [0.54385965, 0.69960474, 0.48128342, ..., 0.11340206, 0.10943396,
        0.39728959]])

In [25]:
X_test

array([[0.68656716, 0.91435768, 0.57142857, 0.85714286, 0.04      ,
        0.20529801, 0.0530303 , 0.85714286, 0.11891892, 0.60840497,
        0.        , 0.27142857, 0.42253521],
       [0.83955224, 0.16624685, 1.        , 0.        , 1.        ,
        0.8013245 , 0.8219697 , 0.48571429, 0.38918919, 0.31709647,
        0.47008547, 0.70952381, 0.78169014],
       [0.66791045, 0.60201511, 0.35714286, 0.57142857, 0.12      ,
        0.05960265, 0.05681818, 0.65714286, 0.17837838, 0.85768863,
        0.15384615, 0.21904762, 0.50704225],
       [0.64925373, 0.35516373, 0.33333333, 0.57142857, 0.04      ,
        0.        , 0.        , 0.88571429, 0.        , 0.82330458,
        0.02564103, 0.16190476, 0.20422535],
       [0.52238806, 0.13853904, 0.3452381 , 0.85714286, 0.04      ,
        0.89403974, 1.        , 0.62857143, 0.61081081, 0.25405922,
        0.12820513, 0.73809524, 0.03802817],
       [0.62313433, 0.64735516, 0.42857143, 0.85714286, 0.84      ,
        0.60233736, 0.26136