In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/My Drive/Salaries.csv')

In [ ]:
df

rank discipline   phd  service     sex  salary
0        Prof          B  56.0     49.0    Male  186960
1        Prof          A  12.0      6.0    Male   93000
2        Prof          A  23.0     20.0    Male  110515
3        Prof          A  40.0     31.0    Male  131205
4        Prof          B  20.0     18.0    Male  104800
..        ...        ...   ...      ...     ...     ...
73       Prof          B  18.0     10.0  Female  105450
74  AssocProf          B  19.0      6.0  Female  104542
75       Prof          B  17.0     17.0  Female  124312
76       Prof          A  28.0     14.0  Female  109954
77       Prof          A  23.0     15.0  Female  109646

[78 rows x 6 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   rank        74 non-null     object 
 1   discipline  75 non-null     object 
 2   phd         76 non-null     float64
 3   service     77 non-null     float64
 4   sex         77 non-null     object 
 5   salary      78 non-null     int64  
dtypes: float64(2), int64(1), object(3)
memory usage: 3.8+ KB


In [ ]:
df.dtypes

rank           object
discipline     object
phd           float64
service       float64
sex            object
salary          int64
dtype: object

In [ ]:
df.describe()

phd    service         salary
count  76.000000  77.000000      78.000000
mean   19.328947  15.207792  108023.782051
std    12.414388  12.139906   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.000000   6.000000   88612.500000
50%    18.000000  15.000000  104671.000000
75%    26.250000  21.000000  126774.750000
max    56.000000  51.000000  186960.000000

In [ ]:
df.groupby('rank').size()

rank
AssocProf    12
AsstProf     18
Prof         44
dtype: int64

In [ ]:
df.groupby('discipline').size()

discipline
A    34
B    41
dtype: int64

In [ ]:
df.groupby('sex').size()

sex
Female    39
Male      38
dtype: int64

In [ ]:
df.isnull().sum()

rank          4
discipline    3
phd           2
service       1
sex           1
salary        0
dtype: int64

In [ ]:
X = df.iloc[:, 0:5].values
y = df.iloc[:, 5].values

In [ ]:
X

array([['Prof', 'B', 56.0, 49.0, 'Male'],
       ['Prof', 'A', 12.0, 6.0, 'Male'],
       ['Prof', 'A', 23.0, 20.0, 'Male'],
       ['Prof', 'A', 40.0, 31.0, 'Male'],
       ['Prof', 'B', 20.0, 18.0, 'Male'],
       ['Prof', 'A', 20.0, 20.0, 'Male'],
       ['AssocProf', 'A', 20.0, 17.0, 'Male'],
       ['Prof', 'A', 18.0, 18.0, 'Male'],
       ['Prof', 'A', 29.0, 19.0, 'Male'],
       ['Prof', 'A', 51.0, 51.0, 'Male'],
       ['Prof', 'B', nan, 33.0, 'Male'],
       ['Prof', 'B', 23.0, 23.0, 'Male'],
       ['AsstProf', 'B', 1.0, 0.0, 'Male'],
       ['Prof', 'B', 35.0, 33.0, 'Male'],
       ['Prof', 'B', 25.0, 19.0, 'Male'],
       ['Prof', 'B', 17.0, nan, 'Male'],
       ['AsstProf', 'B', 8.0, 3.0, 'Male'],
       ['AsstProf', 'B', 4.0, 0.0, nan],
       ['Prof', 'A', 19.0, 7.0, 'Male'],
       ['Prof', 'A', nan, 27.0, 'Male'],
       ['AsstProf', 'B', 4.0, 4.0, 'Male'],
       ['Prof', nan, 33.0, 30.0, 'Male'],
       ['AsstProf', 'A', 4.0, 2.0, 'Male'],
       ['AsstProf', 'A', 2.

In [ ]:
y

array([186960,  93000, 110515, 131205, 104800, 122400,  81285, 126300,
        94350,  57800, 128250, 134778,  88000, 162200, 153750, 150480,
        75044,  92000, 107300, 150500,  92000, 103106,  73000,  85000,
        91100,  99418, 148750, 155865,  91300, 123683, 107008, 155750,
       103275, 120000, 119800, 126933, 146856, 102000,  91000, 129000,
       137000,  74830,  80225,  77000, 151768, 140096,  74692, 103613,
       111512, 122960,  97032, 127512, 105000,  73500,  62884,  72500,
        77500,  72500, 144651, 103994,  92000, 103750, 109650,  91000,
        73300, 117555,  63100,  90450,  77500, 116450,  78500,  71065,
       161101, 105450, 104542, 124312, 109954, 109646])

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.NAN, strategy= 'median', fill_value='None', verbose=1, copy=True)
imputer  = imputer.fit(X[:, 2:4])
X[:, 2:4] = imputer.transform(X[:, 2:4])
X

array([['Prof', 'B', 56.0, 49.0, 'Male'],
       ['Prof', 'A', 12.0, 6.0, 'Male'],
       ['Prof', 'A', 23.0, 20.0, 'Male'],
       ['Prof', 'A', 40.0, 31.0, 'Male'],
       ['Prof', 'B', 20.0, 18.0, 'Male'],
       ['Prof', 'A', 20.0, 20.0, 'Male'],
       ['AssocProf', 'A', 20.0, 17.0, 'Male'],
       ['Prof', 'A', 18.0, 18.0, 'Male'],
       ['Prof', 'A', 29.0, 19.0, 'Male'],
       ['Prof', 'A', 51.0, 51.0, 'Male'],
       ['Prof', 'B', 18.0, 33.0, 'Male'],
       ['Prof', 'B', 23.0, 23.0, 'Male'],
       ['AsstProf', 'B', 1.0, 0.0, 'Male'],
       ['Prof', 'B', 35.0, 33.0, 'Male'],
       ['Prof', 'B', 25.0, 19.0, 'Male'],
       ['Prof', 'B', 17.0, 15.0, 'Male'],
       ['AsstProf', 'B', 8.0, 3.0, 'Male'],
       ['AsstProf', 'B', 4.0, 0.0, nan],
       ['Prof', 'A', 19.0, 7.0, 'Male'],
       ['Prof', 'A', 18.0, 27.0, 'Male'],
       ['AsstProf', 'B', 4.0, 4.0, 'Male'],
       ['Prof', nan, 33.0, 30.0, 'Male'],
       ['AsstProf', 'A', 4.0, 2.0, 'Male'],
       ['AsstProf', 'A',

In [ ]:
pd.DataFrame(X, columns = ['rank','discipline','phd','service','sex']).isnull().sum()

rank          4
discipline    3
phd           0
service       0
sex           1
dtype: int64

In [ ]:
imputer = SimpleImputer(missing_values=np.NAN, strategy= 'most_frequent', fill_value='None', verbose=1, copy=True)
imputer  = imputer.fit(X[:, 0:2])
X[:, 0:2] = imputer.transform(X[:, 0:2])
X

array([['Prof', 'B', 56.0, 49.0, 'Male'],
       ['Prof', 'A', 12.0, 6.0, 'Male'],
       ['Prof', 'A', 23.0, 20.0, 'Male'],
       ['Prof', 'A', 40.0, 31.0, 'Male'],
       ['Prof', 'B', 20.0, 18.0, 'Male'],
       ['Prof', 'A', 20.0, 20.0, 'Male'],
       ['AssocProf', 'A', 20.0, 17.0, 'Male'],
       ['Prof', 'A', 18.0, 18.0, 'Male'],
       ['Prof', 'A', 29.0, 19.0, 'Male'],
       ['Prof', 'A', 51.0, 51.0, 'Male'],
       ['Prof', 'B', 18.0, 33.0, 'Male'],
       ['Prof', 'B', 23.0, 23.0, 'Male'],
       ['AsstProf', 'B', 1.0, 0.0, 'Male'],
       ['Prof', 'B', 35.0, 33.0, 'Male'],
       ['Prof', 'B', 25.0, 19.0, 'Male'],
       ['Prof', 'B', 17.0, 15.0, 'Male'],
       ['AsstProf', 'B', 8.0, 3.0, 'Male'],
       ['AsstProf', 'B', 4.0, 0.0, nan],
       ['Prof', 'A', 19.0, 7.0, 'Male'],
       ['Prof', 'A', 18.0, 27.0, 'Male'],
       ['AsstProf', 'B', 4.0, 4.0, 'Male'],
       ['Prof', 'B', 33.0, 30.0, 'Male'],
       ['AsstProf', 'A', 4.0, 2.0, 'Male'],
       ['AsstProf', 'A',

In [ ]:
imputer = SimpleImputer(missing_values=np.NAN, strategy= 'most_frequent', fill_value='None', verbose=1, copy=True)
imputer  = imputer.fit(X[:, 4:5])
X[:, 4:5] = imputer.transform(X[:, 4:5])
X

array([['Prof', 'B', 56.0, 49.0, 'Male'],
       ['Prof', 'A', 12.0, 6.0, 'Male'],
       ['Prof', 'A', 23.0, 20.0, 'Male'],
       ['Prof', 'A', 40.0, 31.0, 'Male'],
       ['Prof', 'B', 20.0, 18.0, 'Male'],
       ['Prof', 'A', 20.0, 20.0, 'Male'],
       ['AssocProf', 'A', 20.0, 17.0, 'Male'],
       ['Prof', 'A', 18.0, 18.0, 'Male'],
       ['Prof', 'A', 29.0, 19.0, 'Male'],
       ['Prof', 'A', 51.0, 51.0, 'Male'],
       ['Prof', 'B', 18.0, 33.0, 'Male'],
       ['Prof', 'B', 23.0, 23.0, 'Male'],
       ['AsstProf', 'B', 1.0, 0.0, 'Male'],
       ['Prof', 'B', 35.0, 33.0, 'Male'],
       ['Prof', 'B', 25.0, 19.0, 'Male'],
       ['Prof', 'B', 17.0, 15.0, 'Male'],
       ['AsstProf', 'B', 8.0, 3.0, 'Male'],
       ['AsstProf', 'B', 4.0, 0.0, 'Female'],
       ['Prof', 'A', 19.0, 7.0, 'Male'],
       ['Prof', 'A', 18.0, 27.0, 'Male'],
       ['AsstProf', 'B', 4.0, 4.0, 'Male'],
       ['Prof', 'B', 33.0, 30.0, 'Male'],
       ['AsstProf', 'A', 4.0, 2.0, 'Male'],
       ['AsstProf',

In [ ]:
pd.DataFrame(X, columns = ['rank','discipline','phd','service','sex']).isnull().sum()

rank          0
discipline    0
phd           0
service       0
sex           0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
X

array([[2, 'B', 56.0, 49.0, 'Male'],
       [2, 'A', 12.0, 6.0, 'Male'],
       [2, 'A', 23.0, 20.0, 'Male'],
       [2, 'A', 40.0, 31.0, 'Male'],
       [2, 'B', 20.0, 18.0, 'Male'],
       [2, 'A', 20.0, 20.0, 'Male'],
       [0, 'A', 20.0, 17.0, 'Male'],
       [2, 'A', 18.0, 18.0, 'Male'],
       [2, 'A', 29.0, 19.0, 'Male'],
       [2, 'A', 51.0, 51.0, 'Male'],
       [2, 'B', 18.0, 33.0, 'Male'],
       [2, 'B', 23.0, 23.0, 'Male'],
       [1, 'B', 1.0, 0.0, 'Male'],
       [2, 'B', 35.0, 33.0, 'Male'],
       [2, 'B', 25.0, 19.0, 'Male'],
       [2, 'B', 17.0, 15.0, 'Male'],
       [1, 'B', 8.0, 3.0, 'Male'],
       [1, 'B', 4.0, 0.0, 'Female'],
       [2, 'A', 19.0, 7.0, 'Male'],
       [2, 'A', 18.0, 27.0, 'Male'],
       [1, 'B', 4.0, 4.0, 'Male'],
       [2, 'B', 33.0, 30.0, 'Male'],
       [1, 'A', 4.0, 2.0, 'Male'],
       [1, 'A', 2.0, 0.0, 'Male'],
       [2, 'A', 30.0, 23.0, 'Male'],
       [2, 'B', 35.0, 31.0, 'Male'],
       [2, 'A', 38.0, 19.0, 'Male'],
       [2, 'A

In [ ]:
labelencoder_X = LabelEncoder()
X[:, 1] = labelencoder_X.fit_transform(X[:, 1])
X

array([[2, 1, 56.0, 49.0, 'Male'],
       [2, 0, 12.0, 6.0, 'Male'],
       [2, 0, 23.0, 20.0, 'Male'],
       [2, 0, 40.0, 31.0, 'Male'],
       [2, 1, 20.0, 18.0, 'Male'],
       [2, 0, 20.0, 20.0, 'Male'],
       [0, 0, 20.0, 17.0, 'Male'],
       [2, 0, 18.0, 18.0, 'Male'],
       [2, 0, 29.0, 19.0, 'Male'],
       [2, 0, 51.0, 51.0, 'Male'],
       [2, 1, 18.0, 33.0, 'Male'],
       [2, 1, 23.0, 23.0, 'Male'],
       [1, 1, 1.0, 0.0, 'Male'],
       [2, 1, 35.0, 33.0, 'Male'],
       [2, 1, 25.0, 19.0, 'Male'],
       [2, 1, 17.0, 15.0, 'Male'],
       [1, 1, 8.0, 3.0, 'Male'],
       [1, 1, 4.0, 0.0, 'Female'],
       [2, 0, 19.0, 7.0, 'Male'],
       [2, 0, 18.0, 27.0, 'Male'],
       [1, 1, 4.0, 4.0, 'Male'],
       [2, 1, 33.0, 30.0, 'Male'],
       [1, 0, 4.0, 2.0, 'Male'],
       [1, 0, 2.0, 0.0, 'Male'],
       [2, 0, 30.0, 23.0, 'Male'],
       [2, 1, 35.0, 31.0, 'Male'],
       [2, 0, 38.0, 19.0, 'Male'],
       [2, 0, 45.0, 43.0, 'Male'],
       [1, 1, 7.0, 2.0, 'Male'],

In [ ]:
labelencoder_X = LabelEncoder()
X[:, 4] = labelencoder_X.fit_transform(X[:, 4])
X

array([[2, 1, 56.0, 49.0, 1],
       [2, 0, 12.0, 6.0, 1],
       [2, 0, 23.0, 20.0, 1],
       [2, 0, 40.0, 31.0, 1],
       [2, 1, 20.0, 18.0, 1],
       [2, 0, 20.0, 20.0, 1],
       [0, 0, 20.0, 17.0, 1],
       [2, 0, 18.0, 18.0, 1],
       [2, 0, 29.0, 19.0, 1],
       [2, 0, 51.0, 51.0, 1],
       [2, 1, 18.0, 33.0, 1],
       [2, 1, 23.0, 23.0, 1],
       [1, 1, 1.0, 0.0, 1],
       [2, 1, 35.0, 33.0, 1],
       [2, 1, 25.0, 19.0, 1],
       [2, 1, 17.0, 15.0, 1],
       [1, 1, 8.0, 3.0, 1],
       [1, 1, 4.0, 0.0, 0],
       [2, 0, 19.0, 7.0, 1],
       [2, 0, 18.0, 27.0, 1],
       [1, 1, 4.0, 4.0, 1],
       [2, 1, 33.0, 30.0, 1],
       [1, 0, 4.0, 2.0, 1],
       [1, 0, 2.0, 0.0, 1],
       [2, 0, 30.0, 23.0, 1],
       [2, 1, 35.0, 31.0, 1],
       [2, 0, 38.0, 19.0, 1],
       [2, 0, 45.0, 43.0, 1],
       [1, 1, 7.0, 2.0, 1],
       [2, 1, 21.0, 20.0, 1],
       [0, 1, 9.0, 7.0, 1],
       [2, 1, 22.0, 21.0, 1],
       [2, 1, 27.0, 19.0, 1],
       [2, 1, 18.0, 18.0, 1]

In [ ]:
pd.DataFrame(y, columns = ['salary']).isnull().sum()

salary    0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 7)

In [ ]:
X_train

array([[2, 0, 39.0, 36.0, 0],
       [2, 0, 23.0, 20.0, 1],
       [2, 0, 20.0, 8.0, 1],
       [2, 1, 35.0, 33.0, 1],
       [0, 0, 10.0, 8.0, 0],
       [0, 1, 9.0, 7.0, 1],
       [2, 1, 17.0, 18.0, 0],
       [0, 1, 14.0, 7.0, 0],
       [2, 0, 19.0, 7.0, 1],
       [1, 0, 4.0, 2.0, 1],
       [1, 1, 4.0, 4.0, 1],
       [2, 1, 17.0, 17.0, 0],
       [0, 1, 19.0, 6.0, 0],
       [1, 1, 5.0, 0.0, 0],
       [2, 0, 23.0, 15.0, 0],
       [2, 1, 33.0, 30.0, 1],
       [2, 1, 20.0, 14.0, 0],
       [2, 0, 38.0, 19.0, 1],
       [2, 1, 27.0, 19.0, 1],
       [2, 1, 18.0, 18.0, 1],
       [0, 0, 25.0, 22.0, 0],
       [2, 0, 28.0, 7.0, 0],
       [2, 1, 25.0, 25.0, 0],
       [2, 1, 18.0, 33.0, 1],
       [2, 1, 24.0, 15.0, 0],
       [2, 0, 36.0, 19.0, 0],
       [1, 1, 7.0, 2.0, 1],
       [2, 1, 21.0, 20.0, 1],
       [2, 1, 22.0, 21.0, 1],
       [1, 1, 8.0, 3.0, 1],
       [2, 0, 12.0, 0.0, 0],
       [2, 0, 12.0, 6.0, 1],
       [1, 1, 3.0, 3.0, 0],
       [2, 0, 28.0, 14.0, 0],
  

In [ ]:
X_test

array([[0, 1, 13.0, 10.0, 0],
       [2, 1, 45.0, 45.0, 1],
       [0, 1, 12.0, 10.0, 0],
       [1, 1, 4.0, 0.0, 0],
       [0, 0, 13.0, 8.0, 0],
       [1, 1, 1.0, 0.0, 1],
       [2, 0, 45.0, 43.0, 1],
       [2, 1, 17.0, 15.0, 1]], dtype=object)

In [ ]:
y_train

array([137000, 110515, 102000, 162200,  77500, 107008, 122960, 109650,
       107300,  73000,  92000, 124312, 104542,  77000, 109646, 103106,
       127512, 148750, 103275, 120000,  62884, 116450, 140096, 128250,
       161101, 117555,  91300, 123683, 155750,  75044, 105000,  93000,
        92000, 109954, 131205, 126933,  78500,  97032,  74692, 104800,
        91000,  71065,  57800, 119800,  91000,  63100,  73500,  91100,
       122400,  73300, 150500,  81285, 144651,  72500, 134778, 186960,
       151768, 126300, 111512, 129000,  94350,  80225, 105450, 153750,
        72500,  85000,  90450,  99418,  77500, 103613])

In [ ]:
y_test

array([103750, 146856, 103994,  92000,  74830,  88000, 155865, 150480])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [ ]:
X_train

array([[ 0.6821865 , -1.08972474,  1.68311766,  1.84874419, -0.97182532],
       [ 0.6821865 , -1.08972474,  0.31214182,  0.43536979,  1.02899151],
       [ 0.6821865 , -1.08972474,  0.05508385, -0.624661  ,  1.02899151],
       [ 0.6821865 ,  0.91766294,  1.3403737 ,  1.58373649,  1.02899151],
       [-2.12681674, -1.08972474, -0.80177605, -0.624661  , -0.97182532],
       [-2.12681674,  0.91766294, -0.88746204, -0.7129969 ,  1.02899151],
       [ 0.6821865 ,  0.91766294, -0.20197412,  0.25869799, -0.97182532],
       [-2.12681674,  0.91766294, -0.45903209, -0.7129969 , -0.97182532],
       [ 0.6821865 , -1.08972474, -0.03060214, -0.7129969 ,  1.02899151],
       [-0.72231512, -1.08972474, -1.31589199, -1.1546764 ,  1.02899151],
       [-0.72231512,  0.91766294, -1.31589199, -0.9780046 ,  1.02899151],
       [ 0.6821865 ,  0.91766294, -0.20197412,  0.17036209, -0.97182532],
       [-2.12681674,  0.91766294, -0.03060214, -0.8013328 , -0.97182532],
       [-0.72231512,  0.91766294, -1.2

In [ ]:
X_test

array([[-2.12681674,  0.91766294, -0.54471808, -0.44798921, -0.97182532],
       [ 0.6821865 ,  0.91766294,  2.1972336 ,  2.64376728,  1.02899151],
       [-2.12681674,  0.91766294, -0.63040407, -0.44798921, -0.97182532],
       [-0.72231512,  0.91766294, -1.31589199, -1.3313482 , -0.97182532],
       [-2.12681674, -1.08972474, -0.54471808, -0.624661  , -0.97182532],
       [-0.72231512,  0.91766294, -1.57294996, -1.3313482 ,  1.02899151],
       [ 0.6821865 , -1.08972474,  2.1972336 ,  2.46709548,  1.02899151],
       [ 0.6821865 ,  0.91766294, -0.20197412, -0.00630971,  1.02899151]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [ ]:
X_train

array([[1.        , 0.        , 0.68518519, 0.70588235, 0.        ],
       [1.        , 0.        , 0.38888889, 0.39215686, 1.        ],
       [1.        , 0.        , 0.33333333, 0.15686275, 1.        ],
       [1.        , 1.        , 0.61111111, 0.64705882, 1.        ],
       [0.        , 0.        , 0.14814815, 0.15686275, 0.        ],
       [0.        , 1.        , 0.12962963, 0.1372549 , 1.        ],
       [1.        , 1.        , 0.27777778, 0.35294118, 0.        ],
       [0.        , 1.        , 0.22222222, 0.1372549 , 0.        ],
       [1.        , 0.        , 0.31481481, 0.1372549 , 1.        ],
       [0.5       , 0.        , 0.03703704, 0.03921569, 1.        ],
       [0.5       , 1.        , 0.03703704, 0.07843137, 1.        ],
       [1.        , 1.        , 0.27777778, 0.33333333, 0.        ],
       [0.        , 1.        , 0.31481481, 0.11764706, 0.        ],
       [0.5       , 1.        , 0.05555556, 0.        , 0.        ],
       [1.        , 0.        , 0.

In [ ]:
X_test

array([[0.        , 1.        , 0.27272727, 0.22222222, 0.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.        , 1.        , 0.25      , 0.22222222, 0.        ],
       [0.5       , 1.        , 0.06818182, 0.        , 0.        ],
       [0.        , 0.        , 0.27272727, 0.17777778, 0.        ],
       [0.5       , 1.        , 0.        , 0.        , 1.        ],
       [1.        , 0.        , 1.        , 0.95555556, 1.        ],
       [1.        , 1.        , 0.36363636, 0.33333333, 1.        ]])